site_name: All the documents
site_url: https://ganesh-document.github.io/all-documents
repo_url: https://github.com/ganesh-document/all-documents
edit_uri: /tree/main/all-documents
repo_name: Ganesh All Documents
site_author: Ganesh Kinkar Giri
site_description: Ganesh all git docs
use_directory_urls: True

theme:
    name: material
nav:
   - Overview: 
     - Documents:
       - Documents details: Documentsdetails.md
   - AIML:
      - Overview: AIML/aiml-overview.md
      - NVIDIA:
        - NIM Models:
          - Large Language Models:
            - 01-ai: NVIDIA/NIM/Models/LLM-Models/01-ai/01-ai-yi-large.md
            - abacusai: NVIDIA/NIM/Models/LLM-Models/abacusai/abacusai.md
            - aisingapore: NVIDIA/NIM/Models/LLM-Models/aisingapore/aisingapore.md
            - bigcode: NVIDIA/NIM/Models/LLM-Models/bigcode/bigcode.md
            - databricks: NVIDIA/NIM/Models/LLM-Models/databricks/databricks.md
            - deepseek: NVIDIA/NIM/Models/LLM-Models/deepseek/deepseek.md
            - google: NVIDIA/NIM/Models/LLM-Models/google/google.md
            - ibm: NVIDIA/NIM/Models/LLM-Models/ibm/ibm.md
            - mediatek: NVIDIA/NIM/Models/LLM-Models/mediatek/mediatek.md
            - meta: NVIDIA/NIM/Models/LLM-Models/meta/meta.md
            - microsoft: NVIDIA/NIM/Models/LLM-Models/microsoft/microsoft.md
            - mistralai: NVIDIA/NIM/Models/LLM-Models/mistralai/mistralai.md
            - nvidia: NVIDIA/NIM/Models/LLM-Models/nvidia/nvidia.md
            - qwen: NVIDIA/NIM/Models/LLM-Models/qwen/qwen.md
            - rakuten: NVIDIA/NIM/Models/LLM-Models/rakuten/rakuten.md
            - seallms: NVIDIA/NIM/Models/LLM-Models/seallms/seallms.md
            - snowflake: NVIDIA/NIM/Models/LLM-Models/snowflake/snowflake.md
            - upstage: NVIDIA/NIM/Models/LLM-Models/upstage/upstage.md
          - Retrieval Models:
            - baai: NVIDIA/NIM/Models/Retrieval-Models/baai.md
            - nvidia: NVIDIA/NIM/Models/Retrieval-Models/nvidia.md
            - snowflake: NVIDIA/NIM/Models/Retrieval-Models/snowflake.md
          - Visual Models:
            - briaai: NVIDIA/NIM/Models/Visual-Models/briaai.md
            - nvidia: NVIDIA/NIM/Models/Visual-Models/nvidia.md
            - stabilityai: NVIDIA/NIM/Models/Visual-Models/stabilityai.md
          - Multimodal Models:
            - adept: NVIDIA/NIM/Models/Multimodal-Models/adept.md
            - google: NVIDIA/NIM/Models/Multimodal-Models/google.md
            - liuhaotian: NVIDIA/NIM/Models/Multimodal-Models/liuhaotian.md
            - microsoft: NVIDIA/NIM/Models/Multimodal-Models/microsoft.md
            - nvidia: NVIDIA/NIM/Models/Multimodal-Models/nvidia.md
          - Healthcare Models:
            - deepmind: NVIDIA/NIM/Models/Healthcare-Models/deepmind.md
            - ipd: NVIDIA/NIM/Models/Healthcare-Models/ipd.md
            - meta: NVIDIA/NIM/Models/Healthcare-Models/meta.md
            - mit: NVIDIA/NIM/Models/Healthcare-Models/mit.md
            - nvidia: NVIDIA/NIM/Models/Healthcare-Models/nvidia.md
          - Route Optimization Models:
            - nvidia: NVIDIA/NIM/Models/Route-Optimization-Models/nvidia.md
          - Climate Simulation Models:
            - nvidia: NVIDIA/NIM/Models/Route-Climate-Simulation-Models/nvidia.md
      - Supervised:
          - Supervised Overview: AIML/Supervised/Supervised-overview.md
          - Regression:
            - Linear Regression: AIML/Supervised/Linear-Regression.md
            - Decision Tree: AIML/Supervised/Decision-Tree.md
            - Random Forest: AIML/Supervised/Random-Forest.md
            - SVM: AIML/Supervised/SVM.md
            - Naive Bayes: AIML/Supervised/Naive-Bayes.md
            - Gradient Boosting: AIML/Supervised/Gradient-Boosting.md
          - Classification:
            - Classification Overview: AIML/Supervised/Classification-overview.md
            - Logistic Regression: AIML/Supervised/Logistic-Regression.md
            - KNN: AIML/Supervised/KNN.md
      - Unsupervised: 
            - Unsupervised Overview: AIML/Unsupervised/Unsupervised-overview.md
            - K-means: AIML/Unsupervised/K-means.md
            - PCA: AIML/Unsupervised/PCA.md
            - SOM: AIML/Unsupervised/SOM.md
            - ARIMA: AIML/Unsupervised/ARIMA.md
            - SARIMA: AIML/Unsupervised/SARIMA.md
      - Deep Learning:
        - Deep Learning Overview: AIML/DeepLearning/DeepLearning-overview.md
        - Deep Learning Algorithms: AIML/DeepLearning/DeepLearning-algorithms.md
        - Keras: AIML/DeepLearning/Keras.md
        - Tensorflow: AIML/DeepLearning/Tensorflow.md
        - Pytorch: AIML/DeepLearning/Pytorch.md
        - LSTM: AIML/DeepLearning/LSTM.md
        - Autoencoder: AIML/DeepLearning/Autoencoder.md
        - Reinforcement Learning: AIML/DeepLearning/Reinforcement-Learning.md
        - NLP: AIML/DeepLearning/NLP.md
        - BERT: AIML/DeepLearning/BERT.md
        - GPT: AIML/DeepLearning/GPT.md
      - RAG:
        - Vector Database: AIML/RAG/vector_database.md
        - Retrieval augmented generation: AIML/RAG/Retrieval_augmented_generation.md

#theme: readthedocs
theme:
    #name: material
    name: readthedocs
    #features:
    #    - toc.integrate
    #    - navigation.indexes
    #    - content.tabs.link
    #icon:
    #    repo: fontawesome/brands/github-alt

extra_css: [css/extra.css]
markdown_extensions:
    - toc:
        toc_depth: 3
        permalink: "#"
    - tables        
use_directory_urls: false
plugins:
    - search
    - git-revision-date-localized
    - git-authors
