site_name: All the documents
site_url: https://ganesh-document.github.io/all-documents
repo_url: https://github.com/ganesh-document/all-documents
edit_uri: /tree/main/all-documents
repo_name: Ganesh All Documents
site_author: Ganesh Kinkar Giri
site_description: Ganesh all git docs
use_directory_urls: True

theme:
    name: material
nav:
   - Overview: 
     - Documents:
       - Documents details: Documentsdetails.md
   - Cloud:
       - Aws: Cloud/Aws/aws.md
       - Azure: Cloud/Azure/azure.md
       - Gcp: Cloud/Gcp/gcp.md
       - Oci: Cloud/Oci/oci.md
       - Ibm: Cloud/Ibm/ibm.md
   - Devops:
       - Overview: Devops/devopso-verview.md
       - Tools:
          - CI (Continuous Integration):
            - Github Action: Devops/tools/CI/Github-action.md
            - Jenkins: Devops/tools/CI/Jenkins.md
            - TravisCI: Devops/tools/CI/TravisCI.md
            - GitLab: Devops/tools/CI/Gitlab.md
            - TeamCity: Devops/tools/CI/TeamCity.md
            - CircleCI: Devops/tools/CI/CircleCI.md
            - Bamboo: Devops/tools/CI/Bamboo.md
            - Bitbucket: Devops/tools/CI/Bitbucket.md
            - AWS CodePipeline: Devops/tools/CI/AWS-CodePipeline.md
            - Azure Pipelines: Devops/tools/CI/Azure-Pipelines.md
          - CD (Continuous Delivery):
            - Jenkins: Devops/tools/CD/Jenkins.md
            - ArgoCD: Devops/tools/CD/ArgoCD.md
            - GoCD: Devops/tools/CD/GoCD.md
            - Spinnaker: Devops/tools/CD/Spinnaker.md
            - GitLab: Devops/tools/CD/GitLab.md
          - CR (Container Registry):
            - Jfrog artifactory: Devops/tools/CR/Jfrog-artifactory.md
          - SCR (Source Code Repository):
            - Github: Devops/tools/SCR/Github.md
          - CQT (Code Quality Tools):
            - SonarQube: Devops/tools/CQT/Sonarqube.md
   - Securiy:
       - poc: Security/Sesecurity.md
   - Compliance:
       - poc: Compliance/compliance.md
   - DevSecOps:
       - poc: DevSecOps/devsecops.md
   - Micro Service:
       - MicroService/microservice.md

#theme: readthedocs
theme:
    name: material
    features:
        - toc.integrate
        - navigation.indexes
        - content.tabs.link
    icon:
        repo: fontawesome/brands/github-alt

extra_css: [css/extra.css]
markdown_extensions:
    - toc:
        toc_depth: 3
        permalink: "#"
    - tables        
use_directory_urls: false
plugins:
    - search
    - git-revision-date-localized
    - git-authors
