name: ganesh-document/all-documents
on:
  repository_dispatch:
    types: do-build
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GHE_TOKEN: ${{ secrets.GHE_TOKEN }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  WORKSPACE_PATH: ${{ github.workspace }}
  REPO: ${{ github.repository }}
jobs:
    build:
      name: build
      runs-on: [ ubuntu-latest ]
      strategy:
        matrix:
          python_version: [3.9]
      #defaults:
      #  run:
      #    working-directory: ${{ env.WORKSPACE_PATH }}/src/github.com/${{ github.repository }}
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install python3.9
      - name: Make docs
        run: |
          pip install jinja2==3.0.3
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          mkdocs build --verbose --clean
      - name: Publish docs
        if: github.ref == 'refs/heads/master'
        run: |
          git fetch
          mkdocs gh-deploy
