name: build
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GHE_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
           pip install jinja2==3.0.3
           pip install mkdocs
           pip install mkdocs-material
           pip install mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force --clean --verbose
