name: ganesh-document/all-documents
on:
  repository_dispatch:
    types: do-build
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GITHUB_TOKEN: ${{ secrets.GHE_TOKEN }}
  #ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  WORKSPACE_PATH: ${{ github.workspace }}
  REPO: ${{ github.repository }}
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: |
           pip install jinja2==3.0.3
           pip install mkdocs
           pip install mkdocs-material
           pip install mkdocs-git-revision-date-localized-plugin
           mkdocs build --verbose --clean
           #pip install mkdocs mkdocs-gen-files
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy
