name: ganesh-document/all-documents
on:
  repository_dispatch:
    types: do-build
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GHE_TOKEN: ${{ secrets.GHE_TOKEN }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  WORKSPACE_PATH: ${{ github.workspace }}
  REPO: ${{ github.repository }}
jobs:
  tests:
    name: tox on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.6,3.8'

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "pypy3"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] tox tox-gh-actions 
      - name: Make docs
        run: |
          pip install jinja2==3.0.3
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          mkdocs build --verbose --clean
      - name: Publish docs
        if: github.ref == 'refs/heads/master'
        run: |
          git fetch
          mkdocs gh-deploy
